# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 753)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(19, 19, 19);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 70))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom: 1px solid#000;\n"
"    background-color:rgb(0,0,0);\n"
"}\n"
"")
        self.main_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.left_menu_toggle = QtWidgets.QFrame(self.main_header)
        self.left_menu_toggle.setGeometry(QtCore.QRect(0, 10, 100, 57))
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(100, 0))
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.pushButton = QtWidgets.QPushButton(self.left_menu_toggle)
        self.pushButton.setGeometry(QtCore.QRect(1, 1, 71, 61))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton.setStyleSheet("QFrame{\n"
"    background-color:#000;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 10px;    \n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color:#000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(104,151,187)\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/burger_menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(36, 36))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(5)
        self.main_body.setFont(font)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.left_side_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color:#000;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 20px;    \n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color:#000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0,92,157)\n"
"}")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_menu_top = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top.setStyleSheet("QFrame{\n"
"    background-color:#000;\n"
"}\n"
"QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color:#000;\n"
"    color: #fff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(104,151,187)\n"
"}")
        self.left_menu_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top.setObjectName("left_menu_top")
        self.gridLayout = QtWidgets.QGridLayout(self.left_menu_top)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.convert_slide_btn = QtWidgets.QPushButton(self.left_menu_top)
        self.convert_slide_btn.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.convert_slide_btn.setFont(font)
        self.convert_slide_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.convert_slide_btn.setStyleSheet("padding-left: 110;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/arrows.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.convert_slide_btn.setIcon(icon1)
        self.convert_slide_btn.setIconSize(QtCore.QSize(32, 32))
        self.convert_slide_btn.setObjectName("convert_slide_btn")
        self.gridLayout.addWidget(self.convert_slide_btn, 0, 0, 1, 1)
        self.history_slide_btn = QtWidgets.QPushButton(self.left_menu_top)
        self.history_slide_btn.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(10)
        self.history_slide_btn.setFont(font)
        self.history_slide_btn.setStyleSheet("padding-left: 110;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_slide_btn.setIcon(icon2)
        self.history_slide_btn.setIconSize(QtCore.QSize(32, 32))
        self.history_slide_btn.setObjectName("history_slide_btn")
        self.gridLayout.addWidget(self.history_slide_btn, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.left_menu_top)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_items = QtWidgets.QFrame(self.main_body)
        self.center_main_items.setStyleSheet("")
        self.center_main_items.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.center_main_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_items.setObjectName("center_main_items")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_items)
        self.stackedWidget.setGeometry(QtCore.QRect(-300, -10, 1501, 641))
        self.stackedWidget.setObjectName("stackedWidget")
        self.convert_page = QtWidgets.QWidget()
        self.convert_page.setObjectName("convert_page")
        self.input_currency = QtWidgets.QComboBox(self.convert_page)
        self.input_currency.setGeometry(QtCore.QRect(400, 50, 251, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.input_currency.setFont(font)
        self.input_currency.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_currency.setStyleSheet("border: 2px solid rgb(255, 255, 255) ;\n"
"color: rgb(255, 255, 255);\n"
"color: white;\n"
"")
        self.input_currency.setEditable(False)
        self.input_currency.setMaxCount(2147483647)
        self.input_currency.setIconSize(QtCore.QSize(64, 64))
        self.input_currency.setObjectName("input_currency")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("country_icons/usa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_currency.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("country_icons/canada.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_currency.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("country_icons/european-union.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_currency.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("country_icons/bulgaria.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_currency.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("country_icons/sweden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_currency.addItem(icon7, "")
        self.output_currency = QtWidgets.QComboBox(self.convert_page)
        self.output_currency.setGeometry(QtCore.QRect(890, 50, 251, 111))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.output_currency.setFont(font)
        self.output_currency.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.output_currency.setStyleSheet("border: 2px solid rgb(255, 255, 255) ;\n"
"color: rgb(255, 255, 255);\n"
"color: white;\n"
"")
        self.output_currency.setEditable(False)
        self.output_currency.setMaxCount(2147483647)
        self.output_currency.setIconSize(QtCore.QSize(64, 64))
        self.output_currency.setObjectName("output_currency")
        self.output_currency.addItem(icon5, "")
        self.output_currency.addItem(icon4, "")
        self.output_currency.addItem(icon3, "")
        self.output_currency.addItem(icon6, "")
        self.output_currency.addItem(icon7, "")
        self.input_amount = QtWidgets.QLineEdit(self.convert_page)
        self.input_amount.setGeometry(QtCore.QRect(610, 220, 301, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.input_amount.setFont(font)
        self.input_amount.setStyleSheet("border: 2px solid rgb(255, 255, 255) ;\n"
"color: rgb(255, 255, 255);\n"
"color: white;\n"
"")
        self.input_amount.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_amount.setInputMask("")
        self.input_amount.setText("")
        self.input_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_amount.setPlaceholderText("")
        self.input_amount.setObjectName("input_amount")
        self.convert_button = QtWidgets.QPushButton(self.convert_page)
        self.convert_button.setGeometry(QtCore.QRect(590, 370, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.convert_button.setFont(font)
        self.convert_button.setStyleSheet("border: 2px solid rgb(255, 255, 255) ;\n"
"color: rgb(255, 255, 255);\n"
"color: white;")
        self.convert_button.setObjectName("convert_button")
        self.result_label = QtWidgets.QLabel(self.convert_page)
        self.result_label.setGeometry(QtCore.QRect(310, 490, 891, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setStyleSheet("color: white")
        self.result_label.setText("")
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.stackedWidget.addWidget(self.convert_page)
        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.history_listWidget = QtWidgets.QListWidget(self.history_page)
        self.history_listWidget.setGeometry(QtCore.QRect(370, 110, 791, 481))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.history_listWidget.setFont(font)
        self.history_listWidget.setStyleSheet("border: 2px solid rgb(255, 255, 255) ;\n"
"color: white;\n"
"")
        self.history_listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.history_listWidget.setObjectName("history_listWidget")
        self.label = QtWidgets.QLabel(self.history_page)
        self.label.setGeometry(QtCore.QRect(520, 20, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.history_page)
        self.horizontalLayout.addWidget(self.center_main_items)
        self.right_side_menu = QtWidgets.QFrame(self.main_body)
        self.right_side_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.right_side_menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_side_menu.setObjectName("right_side_menu")
        self.label_3 = QtWidgets.QLabel(self.right_side_menu)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 81, 171))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.right_side_menu)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_footer.setStyleSheet("QFrame{\n"
"    background-color:rgb(0,0,0);\n"
"    border-top-color: solid 1px rgb(0,0,0);\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.convert_slide_btn.setText(_translate("MainWindow", "CONVERT"))
        self.history_slide_btn.setText(_translate("MainWindow", "HISTORY"))
        self.input_currency.setItemText(0, _translate("MainWindow", "USD"))
        self.input_currency.setItemText(1, _translate("MainWindow", "CAD"))
        self.input_currency.setItemText(2, _translate("MainWindow", "EUR"))
        self.input_currency.setItemText(3, _translate("MainWindow", "BGN"))
        self.input_currency.setItemText(4, _translate("MainWindow", "SEK"))
        self.output_currency.setItemText(0, _translate("MainWindow", "EUR"))
        self.output_currency.setItemText(1, _translate("MainWindow", "CAD"))
        self.output_currency.setItemText(2, _translate("MainWindow", "USD"))
        self.output_currency.setItemText(3, _translate("MainWindow", "BGN"))
        self.output_currency.setItemText(4, _translate("MainWindow", "SEK"))
        self.convert_button.setText(_translate("MainWindow", "КОНВЕРТУВАТИ"))
        self.label.setText(_translate("MainWindow", "ІСТОРІЯ КОНВЕРТУВАНЬ"))
        self.label_3.setText(_translate("MainWindow", "RIGHT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
